#!/usr/bin/env bash

set -euo pipefail
set -x

echo "# Generated by resolvconf" | sudo tee /etc/resolv.conf
echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
sudo wg-quick up /srv/wg0.conf
sudo chmod +r /etc/resolv.conf
cat /etc/resolv.conf

curl ipinfo.io

# shellcheck disable=SC1091
sudo archlinux-java set java-21-openjdk
archlinux-java status

java -jar HentaiAtHome.jar
