#!/usr/bin/env bash

set -euo pipefail
set -x

echo "# Generated by resolvconf" | sudo tee /etc/resolv.conf
echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
sudo wg-quick up /srv/wg0.conf
cat /etc/resolv.conf

curl -v ipinfo.io

git clone https://github.com/xatier/toy-socks5.git
cd toy-socks5

go build
./toy-socks5 -global

# use python version
# python server.py

# use dante
# sleep 5
# /usr/bin/sockd -f /srv/sockd.conf -p /dev/null
bash
