name: GHCR

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GH_TOKEN }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  ghcr:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/redhat-actions/podman-login
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: '[arch-dev] Build and push'
        working-directory: ./arch-dev
        run: |
          make build
          make push

      - name: '[wireguard] Build and push'
        working-directory: ./wireguard
        run: |
          make build
          make push

      - name: '[eh] Build and push'
        working-directory: ./eh
        run: |
          make build
          make push

      - name: '[consider] Build and push'
        working-directory: ./consider
        run: |
          make build
          make push

      - name: '[write-good] Build and push'
        working-directory: ./write-good
        run: |
          make build
          make push

      - name: '[diffoscope] Build and push'
        working-directory: ./diffoscope-arch
        run: |
          make build
          make push
